// still not sure about wether or not this should go into species or into
// it's own table breed

export const species = [
  { name: "Abyssinian" },
  { name: "Affenpinscher" },
  { name: "Afghan Hound" },
  { name: "Aidi" },
  { name: "Ainu" },
  { name: "Airedale Terrier" },
  { name: "Airedoodle" },
  { name: "Akbash" },
  { name: "Akita" },
  { name: "Akita Shepherd" },
  { name: "Alabai (Central Asian Shepherd)" },
  { name: "Alaskan Husky" },
  { name: "Alaskan Klee Kai" },
  { name: "Alaskan Malamute" },
  { name: "Alaskan Shepherd" },
  { name: "Alpine Dachsbracke" },
  { name: "Alusky" },
  { name: "Amazon Parrot" },
  { name: "American Alsatian" },
  { name: "American Bulldog" },
  { name: "American Cocker Spaniel" },
  { name: "American Coonhound" },
  { name: "American Eskimo Dog" },
  { name: "American Foxhound" },
  { name: "American Hairless Terrier" },
  { name: "American Leopard Hound" },
  { name: "American Pit Bull Terrier" },
  { name: "American Pugabull" },
  { name: "American Staffordshire Terrier" },
  { name: "American Water Spaniel" },
  { name: "Anatolian Shepherd Dog" },
  { name: "Angora Ferret" },
  { name: "Appenzeller Dog" },
  { name: "Apple Head Chihuahua" },
  { name: "Aussiedoodle" },
  { name: "Aussiedor" },
  { name: "Aussiepom" },
  { name: "Australian Bulldog" },
  { name: "Australian Cattle Dog" },
  { name: "Australian Kelpie Dog" },
  { name: "Australian Labradoodle" },
  { name: "Australian Mist" },
  { name: "Australian Retriever" },
  { name: "Australian Shepherd" },
  { name: "Australian Shepherd Mix" },
  { name: "Australian Terrier" },
  { name: "Balinese" },
  { name: "Barbet" },
  { name: "Basenji Dog" },
  { name: "Basenji Mix" },
  { name: "Bassador" },
  { name: "Basset Fauve de Bretagne" },
  { name: "Basset Hound" },
  { name: "Bassetoodle" },
  { name: "Bavarian Mountain Hound" },
  { name: "Bea-Tzu" },
  { name: "Beabull" },
  { name: "Beagador" },
  { name: "Beagle" },
  { name: "Beagle Mix" },
  { name: "Beagle Shepherd" },
  { name: "Beaglier" },
  { name: "Beago" },
  { name: "Bearded Collie" },
  { name: "Bearded Dragon" },
  { name: "Beaski" },
  { name: "Beauceron" },
  { name: "Bedlington Terrier" },
  { name: "Belgian Malinois" },
  { name: "Belgian Malinois Mix" },
  { name: "Belgian Sheepdog" },
  { name: "Belgian Shepherd" },
  { name: "Belgian Tervuren" },
  { name: "Bergamasco" },
  { name: "Berger Picard" },
  { name: "Bernedoodle" },
  { name: "Bernese Mountain Dog" },
  { name: "Bernese Mountain Dog Mix" },
  { name: "Bernese Shepherd" },
  { name: "Betta Fish (Siamese Fighting Fish)" },
  { name: "Bichon Frise" },
  { name: "Bichpoo" },
  { name: "Biewer Terrier" },
  { name: "Birman" },
  { name: "Black And Tan Coonhound" },
  { name: "Black Russian Terrier" },
  { name: "Bladefin Basslet" },
  { name: "Bloodhound" },
  { name: "Blue Lacy Dog" },
  { name: "Blue Picardy Spaniel" },
  { name: "Bluetick Coonhound" },
  { name: "Boggle" },
  { name: "Boglen Terrier" },
  { name: "Bolognese Dog" },
  { name: "Bombay" },
  { name: "Borador" },
  { name: "Border Collie" },
  { name: "Border Collie Mix" },
  { name: "Border Terrier" },
  { name: "Bordoodle" },
  { name: "Borkie" },
  { name: "Boston Terrier" },
  { name: "Bouvier Des Flandres" },
  { name: "Boxador" },
  { name: "Boxer Dog" },
  { name: "Boxer Mix" },
  { name: "Boxerdoodle" },
  { name: "Boxsky" },
  { name: "Boxweiler" },
  { name: "Boykin Spaniel" },
  { name: "Braque du Bourbonnais" },
  { name: "Braque Francais" },
  { name: "Brazilian Terrier" },
  { name: "British Timber" },
  { name: "Brittany" },
  { name: "Brug" },
  { name: "Brussels Griffon" },
  { name: "Budgerigar" },
  { name: "Bull Terrier" },
  { name: "Bulldog" },
  { name: "Bulldog Mix" },
  { name: "Bullmastiff" },
  { name: "Burmese" },
  { name: "Cairn Terrier" },
  { name: "Canaan Dog" },
  { name: "Canadian Eskimo Dog" },
  { name: "Cane Corso" },
  { name: "Carolina Dog" },
  { name: "Cat" },
  { name: "Catahoula Bulldog" },
  { name: "Catahoula Leopard" },
  { name: "Catalan Sheepdog" },
  { name: "Caucasian Shepherd" },
  { name: "Cava Tzu" },
  { name: "Cavador" },
  { name: "Cavalier King Charles Spaniel" },
  { name: "Cavapoo" },
  { name: "Cesky Fousek" },
  { name: "Cesky Terrier" },
  { name: "Chartreux" },
  { name: "Cheagle" },
  { name: "Chesapeake Bay Retriever" },
  { name: "Chihuahua" },
  { name: "Chinese Crested Dog" },
  { name: "Chinese Shar-Pei" },
  { name: "Chinook" },
  { name: "Chipit" },
  { name: "Chipoo" },
  { name: "Chiweenie" },
  { name: "Chorkie" },
  { name: "Chow Chow" },
  { name: "Chow Shepherd" },
  { name: "Cinnamon Ferret" },
  { name: "Clumber Spaniel" },
  { name: "Cockalier" },
  { name: "Cockapoo" },
  { name: "Cockatiel" },
  { name: "Cockatoo" },
  { name: "Cocker Spaniel" },
  { name: "Collie" },
  { name: "Corgidor" },
  { name: "Corgipoo" },
  { name: "Corkie" },
  { name: "Corman Shepherd" },
  { name: "Corn Rex Cat (Cornish Rex)" },
  { name: "Coton de Tulear" },
  { name: "Curly Coated Retriever" },
  { name: "Czechoslovakian Wolfdog" },
  { name: "Dachsador" },
  { name: "Dachshund" },
  { name: "Dachshund Mix" },
  { name: "Dalmadoodle" },
  { name: "Dalmador" },
  { name: "Dalmatian" },
  { name: "Danish Swedish Farmdog" },
  { name: "Dapple Dachshund" },
  { name: "Daug" },
  { name: "Deer Head Chihuahua" },
  { name: "Deutsche Bracke" },
  { name: "Devon Rex" },
  { name: "Doberman Pinscher" },
  { name: "Dog" },
  { name: "Dogo Argentino" },
  { name: "Dogue De Bordeaux" },
  { name: "Dorgi" },
  { name: "Dorkie" },
  { name: "Double Doodle" },
  { name: "Doxiepoo" },
  { name: "Doxle" },
  { name: "Draco Volans Lizard" },
  { name: "Drever" },
  { name: "Dunker" },
  { name: "Eclectus Parrot" },
  { name: "Egyptian Mau" },
  { name: "English Bulldog" },
  { name: "English Cocker Spaniel" },
  { name: "English Cream Golden Retriever" },
  { name: "English Foxhound" },
  { name: "English Pointer" },
  { name: "English Setter" },
  { name: "English Shepherd" },
  { name: "English Springer Spaniel" },
  { name: "Entlebucher Mountain Dog" },
  { name: "Epagneul Pont Audemer" },
  { name: "Eskimo Dog" },
  { name: "Eskipoo" },
  { name: "Estrela Mountain Dog" },
  { name: "Fancy Mouse" },
  { name: "Feist" },
  { name: "Fennec Fox" },
  { name: "Ferret" },
  { name: "Field Spaniel" },
  { name: "Fila Brasileiro" },
  { name: "Finnish Spitz" },
  { name: "Fish" },
  { name: "Flat-Coated Retriever" },
  { name: "Flowerhorn Fish" },
  { name: "Formosan Mountain Dog" },
  { name: "Fox Terrier" },
  { name: "French Bulldog" },
  { name: "French Bulldog Mix" },
  { name: "Frenchton" },
  { name: "Frengle" },
  { name: "Frog" },
  { name: "Gecko" },
  { name: "Gerberian Shepsky" },
  { name: "Gerbil" },
  { name: "German Pinscher" },
  { name: "German Shepherd Guide" },
  { name: "German Shepherd Mix" },
  { name: "German Sheppit" },
  { name: "German Sheprador" },
  { name: "German Shorthaired Pointer" },
  { name: "German Spitz" },
  { name: "Giant Schnauzer" },
  { name: "Giant Schnoodle" },
  { name: "Glechon" },
  { name: "Glen Of Imaal Terrier" },
  { name: "Goberian" },
  { name: "Goldador" },
  { name: "Golden Dox" },
  { name: "Golden Newfie" },
  { name: "Golden Pyrenees" },
  { name: "Golden Retriever" },
  { name: "Golden Retriever Mix" },
  { name: "Golden Saint" },
  { name: "Golden Shepherd" },
  { name: "Goldendoodle" },
  { name: "Goldfish" },
  { name: "Gordon Setter" },
  { name: "Gouldian Finch" },
  { name: "Great Dane" },
  { name: "Great Danoodle" },
  { name: "Great Pyrenees" },
  { name: "Great Pyrenees Mix" },
  { name: "Greater Swiss Mountain Dog" },
  { name: "Greenland Dog" },
  { name: "Greyhound" },
  { name: "Griffonshire" },
  { name: "Groenendael" },
  { name: "Guinea Pig" },
  { name: "Hamster" },
  { name: "Harrier" },
  { name: "Havanese" },
  { name: "Havapoo" },
  { name: "Havashire" },
  { name: "Himalayan" },
  { name: "Hokkaido" },
  { name: "Horgi" },
  { name: "House Finch" },
  { name: "Huntaway" },
  { name: "Huskador" },
  { name: "Huskita" },
  { name: "Husky" },
  { name: "Husky Jack" },
  { name: "Huskydoodle" },
  { name: "Ibizan Hound" },
  { name: "Icelandic Sheepdog" },
  { name: "Iguana" },
  { name: "Irish Doodle" },
  { name: "Irish Setter" },
  { name: "Irish Terrier" },
  { name: "Irish Water Spaniel" },
  { name: "Irish WolfHound" },
  { name: "Italian Greyhound" },
  { name: "Jack Russells" },
  { name: "Jackabee" },
  { name: "Japanese Chin" },
  { name: "Japanese Spitz" },
  { name: "Japanese Terrier" },
  { name: "Javanese" },
  { name: "Kai Ken" },
  { name: "Kangal Shepherd Dog" },
  { name: "Keel-Billed Toucan" },
  { name: "Keeshond" },
  { name: "Kerry Blue Terrier" },
  { name: "King Shepherd" },
  { name: "Kishu" },
  { name: "Koi Fish" },
  { name: "Kooikerhondje" },
  { name: "Koolie" },
  { name: "Kuvasz" },
  { name: "Labahoula" },
  { name: "Labmaraner" },
  { name: "Labradane" },
  { name: "Labradoodle" },
  { name: "Labrador Retriever" },
  { name: "Labraheeler" },
  { name: "Labrottie" },
  { name: "Lakeland Terrier" },
  { name: "Lancashire Heeler" },
  { name: "Lapponian Herder" },
  { name: "Leonberger" },
  { name: "Lhasa Apso" },
  { name: "Lhasapoo" },
  { name: "Lizard" },
  { name: "Loach" },
  { name: "Long-Haired Rottweiler" },
  { name: "Lorikeet" },
  { name: "Lowchen" },
  { name: "Macaw" },
  { name: "Maine Coon" },
  { name: "Mal Shi" },
  { name: "Malchi" },
  { name: "Malteagle" },
  { name: "Maltese" },
  { name: "Maltese Shih Tzu" },
  { name: "Maltipoo" },
  { name: "Manchester Terrier" },
  { name: "Mastador" },
  { name: "Mastiff" },
  { name: "Mastiff Mix" },
  { name: "Meagle" },
  { name: "Miki" },
  { name: "Mini Labradoodle" },
  { name: "Miniature Bull Terrier" },
  { name: "Miniature Pinscher" },
  { name: "Mongrel" },
  { name: "Monitor Lizard" },
  { name: "Morkie" },
  { name: "Moscow Watchdog" },
  { name: "Mountain Cur" },
  { name: "Mountain Feist" },
  { name: "Mourning Dove" },
  { name: "Mouse" },
  { name: "Mudi" },
  { name: "Myna Bird" },
  { name: "Neapolitan Mastiff" },
  { name: "Nebelung" },
  { name: "Newfoundland" },
  { name: "Newfypoo" },
  { name: "Norfolk Terrier" },
  { name: "Northern Inuit Dog" },
  { name: "Norwegian Buhund" },
  { name: "Norwegian Elkhound" },
  { name: "Norwegian Forest" },
  { name: "Norwegian Lundehund" },
  { name: "Norwich Terrier" },
  { name: "Nova Scotia Duck Tolling Retriever" },
  { name: "Old English Sheepdog" },
  { name: "Oscar Fish" },
  { name: "Otterhound" },
  { name: "Papillon" },
  { name: "Parrot" },
  { name: "Parson Russell Terrier" },
  { name: "Parti Schnauzer" },
  { name: "Patterdale Terrier" },
  { name: "Peagle" },
  { name: "Peekapoo" },
  { name: "Pekingese" },
  { name: "Pembroke Welsh Corgi" },
  { name: "Peppermint Angelfish" },
  { name: "Perro De Presa Canario" },
  { name: "Persian" },
  { name: "Peruvian Inca Orchid" },
  { name: "Petit Basset Griffon Vendéen" },
  { name: "Petite Goldendoodle" },
  { name: "Pit Bull" },
  { name: "Pitador" },
  { name: "Pitsky" },
  { name: "Plott Hound Mix" },
  { name: "Pocket Beagle" },
  { name: "Pocket Pitbull" },
  { name: "Pointer" },
  { name: "Pointer Mix" },
  { name: "Polish Lowland Sheepdog" },
  { name: "Polish Tatra Sheepdog" },
  { name: "Pomapoo" },
  { name: "Pomchi" },
  { name: "Pomeagle" },
  { name: "Pomeranian" },
  { name: "Pomsky" },
  { name: "Poochon" },
  { name: "Poodle" },
  { name: "Poogle" },
  { name: "Pudelpointer" },
  { name: "Pug" },
  { name: "Pug Mix" },
  { name: "Pugapoo" },
  { name: "Puggle" },
  { name: "Pugshire" },
  { name: "Pumi" },
  { name: "Purple Finch" },
  { name: "Pyrador" },
  { name: "Pyredoodle" },
  { name: "Rabbit" },
  { name: "Ragamuffin" },
  { name: "Ragdoll" },
  { name: "Raggle" },
  { name: "Rat" },
  { name: "Rat Terrier" },
  { name: "Red Finch" },
  { name: "Red Knee Tarantula" },
  { name: "Redbone Coonhound" },
  { name: "Rooster" },
  { name: "Rottle" },
  { name: "Rottsky" },
  { name: "Rottweiler" },
  { name: "Rottweiler Mix" },
  { name: "Russell Terrier" },
  { name: "Russian Bear Dog" },
  { name: "Russian Blue" },
  { name: "Saarloos Wolfdog" },
  { name: "Sable Black German Shepherd" },
  { name: "Sable Ferret" },
  { name: "Saint Berdoodle" },
  { name: "Saint Bernard" },
  { name: "Saint Shepherd" },
  { name: "Saluki" },
  { name: "Samoyed" },
  { name: "Sapsali" },
  { name: "Schipperke" },
  { name: "Schneagle" },
  { name: "Schnoodle" },
  { name: "Scottish Terrier" },
  { name: "Sealyham Terrier" },
  { name: "Sheepadoodle" },
  { name: "Shepadoodle" },
  { name: "Shepkita" },
  { name: "Shepweiler" },
  { name: "Shiba Inu" },
  { name: "Shiba Inu Mix" },
  { name: "Shih Poo" },
  { name: "Shih Tzu" },
  { name: "Shih Tzu Mix" },
  { name: "Shollie" },
  { name: "Shrimp" },
  { name: "Siamese" },
  { name: "Siberian" },
  { name: "Siberian Husky" },
  { name: "Siberian Retriever" },
  { name: "Siberpoo" },
  { name: "Silky Terrier" },
  { name: "Silver Labrador" },
  { name: "Skye Terrier" },
  { name: "Slovak Cuvac" },
  { name: "Smooth Fox Terrier" },
  { name: "Snake" },
  { name: "Snorkie" },
  { name: "Snowshoe" },
  { name: "Somali" },
  { name: "Spanador" },
  { name: "Spanish Mastiff" },
  { name: "Spanish Water Dog" },
  { name: "Sphynx" },
  { name: "Spinone Italiano" },
  { name: "Springerdoodle" },
  { name: "Stabyhoun" },
  { name: "Staffordshire Bull Terrier" },
  { name: "Standard Schnauzer" },
  { name: "Swedish Elkhound" },
  { name: "Swedish Vallhund" },
  { name: "Taco Terrier" },
  { name: "Tamaskan" },
  { name: "Teddy Roosevelt Terrier" },
  { name: "Tenterfield Terrier" },
  { name: "Terrier" },
  { name: "Texas Heeler" },
  { name: "Thai Ridgeback" },
  { name: "Tibetan Mastiff" },
  { name: "Tibetan Spaniel" },
  { name: "Tibetan Terrier" },
  { name: "Tiffany" },
  { name: "Torkie" },
  { name: "Toucan" },
  { name: "Toy Fox Terrier" },
  { name: "Toy Poodle" },
  { name: "Transylvanian Hound" },
  { name: "Treeing Tennessee Brindle" },
  { name: "Treeing Walker Coonhound" },
  { name: "Turkish Angora" },
  { name: "Utonagan" },
  { name: "Vizsla" },
  { name: "Volpino Italiano" },
  { name: "Weimaraner" },
  { name: "Weimardoodle" },
  { name: "Welsh Corgi" },
  { name: "Welsh Terrier" },
  { name: "West Highland Terrier" },
  { name: "Westiepoo" },
  { name: "Wheaten Terrier" },
  { name: "Whippet" },
  { name: "White Ferret / Albino Ferrets" },
  { name: "Whoodle" },
  { name: "Wire Fox Terrier" },
  { name: "Wirehaired Pointing Griffon" },
  { name: "Wrought Iron Butterflyfish" },
  { name: "Xoloitzcuintli" },
  { name: "Yakutian Laika" },
  { name: "Yoranian" },
  { name: "Yorkie Bichon" },
  { name: "Yorkiepoo" },
  { name: "Yorkshire Terrier" },
  { name: "Zebra Finch" },
  { name: "Zuchon" }
]
