name: Renovate
on:
  schedule:
    - cron: "0 4 * * 1"    

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate Bot
        uses: renovatebot/github-action@v40.3.4
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}